version: '3'

networks:
  tunnel-net:
    driver: bridge

services:
  tunnel:
    build: .
    ports:
      - "2222:2222"
      - "10000-10099:10000-10099"
    networks:
      - tunnel-net
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tunnel.rule=HostRegexp(`{subdomain:[a-z0-9]+}.tunnel.raar.dev`)"
      - "traefik.http.routers.tunnel.entrypoints=web"
      - "traefik.http.services.tunnel.loadbalancer.server.port=10000-10099"
