version: '3'

networks:
  tunnel-net:
    driver: bridge

services:
  tunnel:
    build: .
    ports:
      - "2222:2222"
      - "10000-10099:10000-10099"  # 使用100个端口，支持100个并发连接
    networks:
      - tunnel-net
    restart: always
    security_opt:
      - no-new-privileges:true
