export interface Chain {
  name: string
  chainId: number
  rpc: string[]
}

export const chains: Chain[] = [
  {
    name: 'Ethereum',
    chainId: 1,
    rpc: [
      'https://endpoints.omniatech.io/v1/eth/mainnet/public',
      'https://rpc.ankr.com/eth',
      'https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7',
      'https://ethereum-rpc.publicnode.com',
      'https://1rpc.io/eth',
      'https://rpc.mevblocker.io',
      'https://rpc.flashbots.net/',
      'https://virginia.rpc.blxrbdn.com/',
      'https://uk.rpc.blxrbdn.com/',
      'https://singapore.rpc.blxrbdn.com/',
      'https://eth.rpc.blxrbdn.com/',
      'https://cloudflare-eth.com/',
      'https://eth-mainnet.public.blastapi.io',
      'https://api.securerpc.com/v1',
      'https://eth-pokt.nodies.app',
      'https://eth-mainnet-public.unifra.io',
      'https://ethereum.blockpi.network/v1/rpc/public',
      'https://rpc.payload.de',
      'https://eth.api.onfinality.io/public',
      'https://core.gashawk.io/rpc',
      'https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://rpc.eth.gateway.fm',
      'https://eth.meowrpc.com',
      'https://eth.drpc.org',
      'https://mainnet.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/mainnet',
      'https://eth.merkle.io',
      'https://rpc.lokibuilder.xyz/wallet',
      'https://eth.nodeconnect.org/',
      'https://api.stateless.solutions/ethereum/v1/demo',
      'https://ethereum.rpc.subquery.network/public',
      'https://rpc.graffiti.farm',
    ],
  },
  {
    name: 'Fantom Testnet',
    chainId: 4002,
    rpc: [
      'https://rpc.testnet.fantom.network/',
      'https://endpoints.omniatech.io/v1/fantom/testnet/public',
      'https://rpc.ankr.com/fantom_testnet',
      'https://fantom-testnet.public.blastapi.io',
      'https://fantom-testnet-rpc.publicnode.com',
      'https://fantom.api.onfinality.io/public',
    ],
  },
  {
    name: 'Avalanche Fuji',
    chainId: 43113,
    rpc: [
      'https://api.avax-test.network/ext/bc/C/rpc',
      'https://endpoints.omniatech.io/v1/avax/fuji/public',
      'https://rpc.ankr.com/avalanche_fuji',
      'https://ava-testnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-fuji-c-chain-rpc.publicnode.com',
      'https://avalanche-fuji.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Polygon Amoy',
    chainId: 80002,
    rpc: [
      'https://rpc-amoy.polygon.technology',
      'https://polygon-amoy.blockpi.network/v1/rpc/public',
      'https://rpc.ankr.com/polygon_amoy',
      'https://polygon-amoy.drpc.org',
    ],
  },
  {
    name: 'Binance Smart Chain',
    chainId: 56,
    rpc: [
      'https://bsc-dataseed.bnbchain.org/',
      'https://bsc-dataseed1.defibit.io/',
      'https://bsc-dataseed1.ninicoin.io/',
      'https://bsc-dataseed2.defibit.io/',
      'https://bsc-dataseed3.defibit.io/',
      'https://bsc-dataseed4.defibit.io/',
      'https://bsc-dataseed2.ninicoin.io/',
      'https://bsc-dataseed3.ninicoin.io/',
      'https://bsc-dataseed4.ninicoin.io/',
      'https://bsc-dataseed1.bnbchain.org/',
      'https://bsc-dataseed2.bnbchain.org/',
      'https://bsc-dataseed3.bnbchain.org/',
      'https://bsc-dataseed4.bnbchain.org/',
      'https://rpc-bsc.48.club',
      'https://koge-rpc-bsc.48.club',
      'https://endpoints.omniatech.io/v1/bsc/mainnet/public',
      'https://bsc-pokt.nodies.app',
      'https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3',
      'https://rpc.ankr.com/bsc',
      'https://bscrpc.com',
      'https://binance.nodereal.io',
      'https://bsc-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://1rpc.io/bnb',
      'https://bsc.rpc.blxrbdn.com/',
      'https://bsc.blockpi.network/v1/rpc/public',
      'https://bnb.api.onfinality.io/public',
      'https://bsc-rpc.publicnode.com',
      'https://bsc-mainnet.public.blastapi.io',
      'https://bsc.meowrpc.com',
      'https://bsc.drpc.org',
      'https://bnb.rpc.subquery.network/public',
    ],
  },
  {
    name: 'Binance Smart Chain Testnet',
    chainId: 97,
    rpc: [
      'https://endpoints.omniatech.io/v1/bsc/testnet/public',
      'https://bsc-testnet.public.blastapi.io',
      'https://bsc-testnet-rpc.publicnode.com',
      'https://bsc-testnet.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Avalanche',
    chainId: 43114,
    rpc: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche.public-rpc.com',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
      'https://1rpc.io/avax/c',
      'https://avalanche.blockpi.network/v1/rpc/public',
      'https://avax-pokt.nodies.app/ext/bc/C/rpc',
      'https://avalanche.api.onfinality.io/public/ext/bc/C/rpc',
      'https://endpoints.omniatech.io/v1/avax/mainnet/public',
      'https://avax.meowrpc.com',
      'https://avalanche.drpc.org',
    ],
  },
  {
    name: 'Fantom',
    chainId: 250,
    rpc: [
      'https://rpcapi.fantom.network',
      'https://endpoints.omniatech.io/v1/fantom/mainnet/public',
      'https://fantom-pokt.nodies.app',
      'https://rpc.ftm.tools/',
      'https://rpc.ankr.com/fantom',
      'https://rpc.fantom.network',
      'https://rpc2.fantom.network',
      'https://rpc3.fantom.network',
      'https://fantom-mainnet.public.blastapi.io',
      'https://1rpc.io/ftm',
      'https://fantom.blockpi.network/v1/rpc/public',
      'https://fantom-rpc.publicnode.com',
      'https://fantom.drpc.org',
    ],
  },
  {
    name: 'Polygon',
    chainId: 137,
    rpc: [
      'https://rpc.ankr.com/polygon',
      'https://endpoints.omniatech.io/v1/matic/mainnet/public',
      'https://polygon-rpc.com',
      'https://rpc-mainnet.matic.quiknode.pro',
      'https://polygon-pokt.nodies.app',
      'https://polygon-mainnet.public.blastapi.io',
      'https://1rpc.io/matic',
      'https://polygon-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf',
      'https://polygon-bor-rpc.publicnode.com',
      'https://polygon.blockpi.network/v1/rpc/public',
      'https://polygon.api.onfinality.io/public',
      'https://polygon.rpc.blxrbdn.com/',
      'https://polygon.drpc.org',
      'https://polygon.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/polygon',
      'https://polygon.meowrpc.com',
      'https://polygon.rpc.subquery.network/public',
    ],
  },
  {
    name: 'Cronos',
    chainId: 25,
    rpc: [
      'https://evm.cronos.org',
      'https://cronos.blockpi.network/v1/rpc/public',
      'https://cronos-evm-rpc.publicnode.com',
      'https://rpc.vvs.finance',
      'https://mmf-rpc.xstaking.sg',
      'https://rpc.nebkas.ro',
    ],
  },
  {
    name: 'Arbitrum',
    chainId: 42161,
    rpc: [
      'https://arb1.arbitrum.io/rpc',
      'https://rpc.ankr.com/arbitrum',
      'https://arb-pokt.nodies.app',
      'https://arbitrum.blockpi.network/v1/rpc/public',
      'https://arbitrum-one.public.blastapi.io',
      'https://endpoints.omniatech.io/v1/arbitrum/one/public',
      'https://arb-mainnet-public.unifra.io',
      'https://arbitrum-one-rpc.publicnode.com',
      'https://arbitrum.meowrpc.com',
      'https://arbitrum.drpc.org',
      'https://api.stateless.solutions/arbitrum-one/v1/demo',
      'https://arbitrum.rpc.subquery.network/public',
    ],
  },
  {
    name: 'Arbitrum Nova',
    chainId: 42170,
    rpc: [
      'https://nova.arbitrum.io/rpc',
      'https://arbitrum-nova.public.blastapi.io',
      'https://arbitrum-nova.blockpi.network/v1/rpc/public',
      'https://arbitrum-nova-rpc.publicnode.com',
      'https://arbitrum-nova.drpc.org',
    ],
  },
  {
    name: 'Arbitrum Sepolia',
    chainId: 421614,
    rpc: [
      'https://arbitrum-sepolia.blockpi.network/v1/rpc/public ',
      'https://endpoints.omniatech.io/v1/arbitrum/sepolia/public',
    ],
  },
  {
    name: 'Klaytn',
    chainId: 8217,
    rpc: [
      'https://public-en-cypress.klaytn.net',
      'https://rpc.ankr.com/klaytn ',
      'https://klaytn.blockpi.network/v1/rpc/public',
      'https://1rpc.io/klay',
      'https://klaytn-pokt.nodies.app',
      'https://klaytn.drpc.org',
    ],
  },
  {
    name: 'Harmony',
    chainId: 1666600000,
    rpc: [
      'https://api.harmony.one',
      'https://a.api.s0.t.hmny.io',
      'https://api.s0.t.hmny.io',
      'https://rpc.ankr.com/harmony',
      'https://1rpc.io/one',
      'https://hmyone-pokt.nodies.app',
      'https://endpoints.omniatech.io/v1/harmony/mainnet-0/public',
      'https://harmony-0.drpc.org',
    ],
  },
  {
    name: 'Blast Sepolia',
    chainId: 168587773,
    rpc: ['https://blast-sepolia.blockpi.network/v1/rpc/public'],
  },
  {
    name: 'Blast',
    chainId: 81457,
    rpc: [
      'https://rpc.blast.io',
      'https://blast.din.dev/rpc',
      'https://blastl2-mainnet.public.blastapi.io',
      'https://blast.blockpi.network/v1/rpc/public',
      'https://blast.blockpi.network/v1/rpc/public',
      'https://rpc.ankr.com/blast',
      'https://rpc.envelop.is/blast',
      'https://blast-rpc.publicnode.com',
      'https://blast.drpc.org',
    ],
  },
  {
    name: 'OP BNB',
    chainId: 204,
    rpc: [
      'https://opbnb-mainnet-rpc.bnbchain.org',
      'https://opbnb.drpc.org',
      'https://opbnb-rpc.publicnode.com',
      'https://1rpc.io/opbnb',
    ],
  },
  {
    name: 'Harmony Testnet',
    chainId: 1666700000,
    rpc: ['https://endpoints.omniatech.io/v1/harmony/testnet-0/public'],
  },
  {
    name: 'Aurora',
    chainId: 1313161554,
    rpc: [
      'https://mainnet.aurora.dev',
      'https://endpoints.omniatech.io/v1/aurora/mainnet/public',
      'https://1rpc.io/aurora',
      'https://aurora.drpc.org',
    ],
  },
  {
    name: 'Aurora Testnet',
    chainId: 1313161555,
    rpc: ['https://endpoints.omniatech.io/v1/aurora/testnet/public'],
  },
  {
    name: 'Heco',
    chainId: 128,
    rpc: ['https://http-mainnet.hecochain.com'],
  },
  {
    name: 'Bahamut',
    chainId: 5165,
    rpc: [
      'https://rpc1.bahamut.io',
      'https://rpc2.bahamut.io',
      'https://bahamut-rpc.publicnode.com',
      'https://Bahamut-mainnet-2h93.zeeve.net',
    ],
  },
  {
    name: 'Celo',
    chainId: 42220,
    rpc: [
      'https://forno.celo.org',
      'https://rpc.ankr.com/celo',
      'https://1rpc.io/celo',
      'https://celo.drpc.org',
    ],
  },
  {
    name: 'Optimism',
    chainId: 10,
    rpc: [
      'https://mainnet.optimism.io/',
      'https://optimism-mainnet.public.blastapi.io',
      'https://rpc.ankr.com/optimism',
      'https://1rpc.io/op',
      'https://op-pokt.nodies.app',
      'https://optimism.blockpi.network/v1/rpc/public',
      'https://endpoints.omniatech.io/v1/op/mainnet/public',
      'https://optimism.api.onfinality.io/public',
      'https://optimism-rpc.publicnode.com',
      'https://optimism.meowrpc.com',
      'https://optimism.drpc.org',
      'https://optimism.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/optimism',
      'https://api.stateless.solutions/optimism/v1/demo',
      'https://optimism.rpc.subquery.network/public',
    ],
  },
  {
    name: 'Optimism Sepolia',
    chainId: 11155420,
    rpc: [
      'https://optimism-sepolia.blockpi.network/v1/rpc/public',
      'https://public.stackup.sh/api/v1/node/optimism-sepolia',
      'https://endpoints.omniatech.io/v1/op/sepolia/public',
    ],
  },
  {
    name: 'Merlin',
    chainId: 4200,
    rpc: ['https://merlin.blockpi.network/v1/rpc/public'],
  },
  {
    name: 'Metis Andromeda',
    chainId: 1088,
    rpc: [
      'https://andromeda.metis.io/?owner=1088',
      'https://metis-mainnet.public.blastapi.io',
      'https://metis.api.onfinality.io/public',
      'https://metis-pokt.nodies.app',
      'https://metis.drpc.org',
    ],
  },
  {
    name: 'Gnosis',
    chainId: 100,
    rpc: [
      'https://rpc.gnosischain.com',
      'https://xdai-archive.blockscout.com',
      'https://gnosis-pokt.nodies.app',
      'https://rpc.gnosis.gateway.fm',
      'https://gnosis-mainnet.public.blastapi.io',
      'https://rpc.ankr.com/gnosis',
      'https://rpc.ap-southeast-1.gateway.fm/v4/gnosis/non-archival/mainnet',
      'https://gnosis.blockpi.network/v1/rpc/public',
      'https://gnosis.api.onfinality.io/public',
      'https://gnosis.drpc.org',
      'https://endpoints.omniatech.io/v1/gnosis/mainnet/public',
      'https://gnosis-rpc.publicnode.com',
      'https://1rpc.io/gnosis',
    ],
  },
  {
    name: 'Gnosis Chiado Testnet',
    chainId: 10200,
    rpc: [
      'https://rpc.chiadochain.net',
      'https://rpc.chiado.gnosis.gateway.fm',
      'https://endpoints.omniatech.io/v1/gnosis/chiado/public',
      'https://gnosis-chiado-rpc.publicnode.com',
      'https://1rpc.io/gnosis',
    ],
  },
  {
    name: 'Moonriver',
    chainId: 1285,
    rpc: [
      'https://moonriver.api.onfinality.io/public',
      'https://moonriver.unitedbloc.com:2000',
      'https://moonriver.public.blastapi.io',
      'https://moonriver-rpc.dwellir.com',
      'https://moonriver-rpc.publicnode.com',
      'https://moonriver.public.curie.radiumblock.co/http',
      'https://moonriver.drpc.org',
    ],
  },
  {
    name: 'Oasis Emerald',
    chainId: 42262,
    rpc: ['https://emerald.oasis.dev/', 'https://1rpc.io/oasis/emerald'],
  },
  {
    name: 'Telos',
    chainId: 40,
    rpc: [
      'https://mainnet.telos.net/evm',
      'https://mainnet15.telos.net/evm',
      'https://rpc3.us.telos.net/evm',
      'https://evm.telos.detroitledger.tech/evm',
      'https://mainnet-us.telos.net/evm',
      'https://mainnet-eu.telos.net/evm',
      'https://mainnet-asia.telos.net/evm',
      'https://1rpc.io/telos/evm',
      'https://telos.drpc.org',
    ],
  },
  {
    name: 'Moonbeam',
    chainId: 1284,
    rpc: [
      'https://rpc.api.moonbeam.network',
      'https://moonbeam.api.onfinality.io/public',
      'https://moonbeam.unitedbloc.com:3000',
      'https://moonbeam.public.blastapi.io',
      'https://rpc.ankr.com/moonbeam',
      'https://1rpc.io/glmr',
      'https://moonbeam-rpc.dwellir.com',
      'https://endpoints.omniatech.io/v1/moonbeam/mainnet/public',
      'https://moonbeam-rpc.publicnode.com',
      'https://moonbeam.public.curie.radiumblock.co/http',
      'https://moonbeam.drpc.org',
    ],
  },
  {
    name: 'Rootstock',
    chainId: 30,
    rpc: [
      'https://mycrypto.rsk.co',
      'https://public-node.rsk.co',
      'https://rootstock.drpc.org',
    ],
  },
  {
    name: 'IoTeX',
    chainId: 4689,
    rpc: [
      'https://rpc.ankr.com/iotex',
      'https://babel-api.mainnet.iotex.io',
      'https://babel-api.mainnet.iotex.one',
      'https://babel-api.fastblocks.io',
      'https://iotexrpc.com',
      'https://iotex-network.rpc.thirdweb.com',
      'https://iotex.api.onfinality.io/public',
    ],
  },
  {
    name: 'OKTC',
    chainId: 66,
    rpc: [
      'https://exchainrpc.okex.org',
      'https://oktc-mainnet.public.blastapi.io',
      'https://okt-chain.api.onfinality.io/public',
      'https://1rpc.io/oktc',
      'https://oktc.drpc.org',
    ],
  },
  {
    name: 'Boba Network',
    chainId: 288,
    rpc: [
      'https://mainnet.boba.network/',
      'https://boba-ethereum.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/boba-ethereum',
      'https://1rpc.io/boba/eth',
      'https://boba-eth.drpc.org',
    ],
  },
  {
    name: 'KCC',
    chainId: 321,
    rpc: ['https://rpc-mainnet.kcc.network', 'https://kcc-rpc.com'],
  },
  {
    name: 'Velas',
    chainId: 106,
    rpc: ['https://evmexplorer.velas.com/rpc'],
  },
  {
    name: 'smartBCH',
    chainId: 10000,
    rpc: [
      'https://smartbch.fountainhead.cash/mainnet',
      'https://global.uat.cash',
      'https://rpc.uatvo.com',
    ],
  },
  {
    name: 'Songbird',
    chainId: 19,
    rpc: [
      'https://songbird-api.flare.network/ext/C/rpc',
      'https://rpc.ftso.au/songbird',
      'https://songbird.solidifi.app/ext/C/rpc',
    ],
  },
  {
    name: 'Fuse',
    chainId: 122,
    rpc: [
      'https://rpc.fuse.io',
      'https://fuse-pokt.nodies.app',
      'https://fuse-mainnet.chainstacklabs.com',
      'https://fuse.api.onfinality.io/public',
      'https://fuse.liquify.com',
      'https://fuse.drpc.org',
    ],
  },
  {
    name: 'Shiden',
    chainId: 336,
    rpc: [
      'https://rpc.shiden.astar.network:8545/',
      'https://shiden.public.blastapi.io',
      'https://shiden-rpc.dwellir.com',
      'https://shiden.api.onfinality.io/public',
      'https://shiden.public.curie.radiumblock.co/http',
    ],
  },
  {
    name: 'Astar',
    chainId: 592,
    rpc: [
      'https://evm.astar.network/',
      'https://rpc.astar.network:8545',
      'https://astar.public.blastapi.io',
      'https://getblock.io/nodes/bsc/',
      'https://1rpc.io/astr',
      'https://astar-mainnet.g.alchemy.com/v2/demo',
      'https://astar.api.onfinality.io/public',
      'https://astar-rpc.dwellir.com',
      'https://astar.public.curie.radiumblock.co/http',
    ],
  },
  {
    name: 'CoinEx Smart Chain',
    chainId: 52,
    rpc: [
      'https://rpc.coinex.net/',
      'https://rpc1.coinex.net/',
      'https://rpc2.coinex.net/',
      'https://rpc3.coinex.net/',
      'https://rpc4.coinex.net/',
    ],
  },
  {
    name: 'ThunderCore',
    chainId: 108,
    rpc: [
      'https://mainnet-rpc.thundercore.com',
      'https://thundercore.drpc.org',
    ],
  },
  {
    name: 'Elastos Smart Chain',
    chainId: 20,
    rpc: [
      'https://api.elastos.io/esc',
      'https://api.trinity-tech.io/esc',
      'https://api2.elastos.io/esc',
      'https://api2.elastos.net/esc',
      'https://api2.elastos.io/eth',
      'https://api2.elastos.net/eth',
      'https://rpc.glidefinance.io/',
    ],
  },
  {
    name: 'Meter',
    chainId: 82,
    rpc: [
      'https://rpc.meter.io',
      'https://rpc-meter.jellypool.xyz/',
      'https://meter.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Viction',
    chainId: 88,
    rpc: [
      'https://rpc.tomochain.com',
      'https://viction.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Syscoin',
    chainId: 57,
    rpc: [
      'https://rpc.syscoin.org',
      'https://rpc.ankr.com/syscoin',
      'https://syscoin-evm.publicnode.com',
    ],
  },
  {
    name: 'ZYX',
    chainId: 55,
    rpc: [
      'https://rpc-1.zyx.network/',
      'https://rpc-2.zyx.network/',
      'https://rpc-3.zyx.network/',
      'https://rpc-5.zyx.network/',
    ],
  },
  {
    name: 'Palm',
    chainId: 11297108109,
    rpc: [
      'https://palm-mainnet.infura.io/v3/3a961d6501e54add9a41aa53f15de99b',
      'https://palm-mainnet.public.blastapi.io',
    ],
  },
  {
    name: 'Holesky',
    chainId: 17000,
    rpc: [
      'https://ethereum-holesky.blockpi.network/v1/rpc/public',
      'https://ethereum-holesky-rpc.publicnode.com',
    ],
  },
  {
    name: 'Crab Network',
    chainId: 44,
    rpc: ['https://crab.api.onfinality.io/public'],
  },
  {
    name: 'XinFin Network',
    chainId: 50,
    rpc: [
      'https://rpc.xdcrpc.com',
      'https://rpc1.xinfin.network',
      'https://erpc.xinfin.network',
      'https://erpc.xdcrpc.com',
      'https://rpc.xdc.org',
      'https://earpc.xinfin.network/',
      'https://erpc.xinfin.network/',
      'https://rpc.ankr.com/xdc',
    ],
  },
  {
    name: 'XinFin Apothem Testnet',
    chainId: 51,
    rpc: [
      'https://erpc.apothem.network',
      'https://apothem.xdcrpc.com',
      'https://earpc.apothem.network/',
      'https://erpc.apothem.network/',
    ],
  },
  {
    name: 'Ontology',
    chainId: 58,
    rpc: [
      'https://dappnode1.ont.io:10339',
      'https://dappnode2.ont.io:10339',
      'https://dappnode3.ont.io:10339',
      'https://dappnode4.ont.io:10339',
    ],
  },
  {
    name: 'EOS EVM Testnet',
    chainId: 15557,
    rpc: ['https://api.testnet.evm.eosnetwork.com'],
  },
  {
    name: 'EOS EVM',
    chainId: 17777,
    rpc: ['https://api.evm.eosnetwork.com'],
  },
  {
    name: 'Ethereum Classic',
    chainId: 61,
    rpc: [
      'https://etc.mytokenpocket.vip',
      'https://rpc.etcinscribe.com',
      'https://etc.etcdesktop.com',
      'https://besu-at.etc-network.info',
      'https://geth-at.etc-network.info',
      'https://services.tokenview.io/vipapi/nodeservice/etc?apikey=qVHq2o6jpaakcw3lRstl',
      'https://etc.rivet.link',
    ],
  },
  {
    name: 'Mordor Testnet',
    chainId: 63,
    rpc: [
      'https://rpc.mordor.etccooperative.org',
      'https://geth-mordor.etc-network.info',
    ],
  },
  {
    name: 'Nova Network',
    chainId: 87,
    rpc: ['https://rpc.novanetwork.io:9070', 'https://dev.rpc.novanetwork.io/'],
  },
  {
    name: 'Manta Pacific',
    chainId: 169,
    rpc: [
      'https://pacific-rpc.manta.network/http',
      'https://1rpc.io/manta',
      'https://manta-pacific-gascap.calderachain.xyz/http',
      'https://www.tencentcloud-rpc.com/v2/manta/manta-rpc',
      'https://r1.pacific.manta.systems/http',
      'https://manta.nirvanalabs.xyz/mantapublic',
      'https://manta-pacific.drpc.org',
    ],
  },
  {
    name: 'PulseChain',
    chainId: 369,
    rpc: [
      'https://rpc.pulsechain.com',
      'https://pulsechain-rpc.publicnode.com',
      'https://rpc-pulsechain.g4mm4.io',
    ],
  },
  {
    name: 'Karura',
    chainId: 686,
    rpc: [
      'https://eth-rpc-karura.aca-staging.network',
      'https://rpc.evm.karura.network',
      'https://karura.api.onfinality.io/public',
    ],
  },
  {
    name: 'Klaytn Baobab Testnet',
    chainId: 1001,
    rpc: [
      'https://public-en-baobab.klaytn.net',
      'https://public-en.kairos.node.kaia.io',
      'https://klaytn-baobab.g.allthatnode.com/full/evm',
      'https://rpc.ankr.com/klaytn_testnet',
      'https://klaytn-baobab.blockpi.network/v1/rpc/public',
      'https://klaytn.api.onfinality.io/public',
    ],
  },
  {
    name: 'Conflux eSpace',
    chainId: 1030,
    rpc: [
      'https://evm.confluxrpc.com',
      'https://conflux-espace-public.unifra.io',
      'https://conflux-espace.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Core Blockchain',
    chainId: 1116,
    rpc: [
      'https://rpc.coredao.org',
      'https://core.public.infstones.com',
      'https://1rpc.io/core',
      'https://rpc.ankr.com/core',
      'https://core.drpc.org',
    ],
  },
  {
    name: 'DeFiChain EVM Network Testnet',
    chainId: 1131,
    rpc: [
      'https://dmc.mydefichain.com/testnet',
      'https://dmc01.mydefichain.com/testnet',
      'https://eth.testnet.ocean.jellyfishsdk.com/',
    ],
  },
  {
    name: 'ZKsync Era Sepolia Testnet',
    chainId: 300,
    rpc: [
      'https://zksync-era-sepolia.blockpi.network/v1/rpc/public',
      'https://endpoints.omniatech.io/v1/zksync-era/sepolia/public',
    ],
  },
  {
    name: 'ZKsync Era',
    chainId: 324,
    rpc: [
      'https://zksync-era.blockpi.network/v1/rpc/public',
      'https://go.getblock.io/f76c09905def4618a34946bf71851542',
      'https://zksync.meowrpc.com',
      'https://zksync.drpc.org',
      'https://endpoints.omniatech.io/v1/zksync-era/mainnet/public',
    ],
  },
  {
    name: 'X Layer',
    chainId: 196,
    rpc: [
      'https://rpc.xlayer.tech',
      'https://xlayerrpc.okx.com',
      'https://endpoints.omniatech.io/v1/xlayer/mainnet/public',
    ],
  },
  {
    name: 'X Layer Testnet',
    chainId: 195,
    rpc: ['https://endpoints.omniatech.io/v1/xlayer/testnet/public'],
  },
  {
    name: 'Moonbase Alpha',
    chainId: 1287,
    rpc: [
      'https://rpc.testnet.moonbeam.network',
      'https://moonbase.unitedbloc.com:1000',
      'https://moonbase-alpha.public.blastapi.io',
      'https://moonbeam-alpha.api.onfinality.io/public',
      'https://moonbase-alpha.drpc.org',
    ],
  },
  {
    name: 'Living Assets Mainnet',
    chainId: 1440,
    rpc: [
      'https://beta.mainnet.livingassets.io/rpc',
      'https://gamma.mainnet.livingassets.io/rpc',
    ],
  },
  {
    name: 'Polygon zkEVM Testnet',
    chainId: 1442,
    rpc: [
      'https://api.zan.top/node/v1/polygonzkevm/testnet/public',
      'https://endpoints.omniatech.io/v1/polygon-zkevm/testnet/public',
    ],
  },
  {
    name: 'LightLink Phoenix Mainnet',
    chainId: 1890,
    rpc: ['https://endpoints.omniatech.io/v1/lightlink/phoenix/public'],
  },
  {
    name: 'LightLink Pegasus Testnet',
    chainId: 1891,
    rpc: ['https://endpoints.omniatech.io/v1/lightlink/pegasus/public'],
  },
  {
    name: 'Dogechain Mainnet',
    chainId: 2000,
    rpc: [
      'https://rpc.dogechain.dog',
      'https://rpc-us.dogechain.dog',
      'https://rpc-sg.dogechain.dog',
      'https://rpc.dogechain.dog',
      'https://rpc01-sg.dogechain.dog',
      'https://rpc02-sg.dogechain.dog',
      'https://rpc03-sg.dogechain.dog',
    ],
  },
  {
    name: 'Edgeware',
    chainId: 2021,
    rpc: [
      'https://mainnet2.edgewa.re/evm',
      'https://mainnet3.edgewa.re/evm',
      'https://edgeware-evm0.jelliedowl.net/',
      'https://edgeware-evm1.jelliedowl.net/',
      'https://edgeware-evm2.jelliedowl.net/',
      'https://edgeware-evm3.jelliedowl.net/',
      'https://edgeware.api.onfinality.io/public',
    ],
  },
  {
    name: 'ZetaChain Athens Testnet',
    chainId: 7001,
    rpc: [
      'https://zetachain-athens-evm.blockpi.network/v1/rpc/public',
      'https://7001.rpc.thirdweb.com',
      'https://zetachain-athens.g.allthatnode.com/archive/evm',
      'https://zeta-chain-testnet.drpc.org',
      'https://zetachain-testnet.public.blastapi.io',
    ],
  },
  {
    name: 'ZetaChain',
    chainId: 7000,
    rpc: [
      'https://zetachain-evm.blockpi.network/v1/rpc/public',
      'https://zetachain-mainnet.g.allthatnode.com/archive/evm',
      'https://zeta-chain.drpc.org',
      'https://zetachain-mainnet.public.blastapi.io',
      'https://7000.rpc.thirdweb.com',
    ],
  },
  {
    name: 'Kava EVM',
    chainId: 2222,
    rpc: [
      'https://evm.kava.io',
      'https://kava.api.onfinality.io/public',
      'https://kava-evm-rpc.publicnode.com',
      'https://kava-pokt.nodies.app',
      'https://evm.kava.chainstacklabs.com',
      'https://rpc.ankr.com/kava_evm',
      'https://evm.kava-rpc.com',
      'https://kava.drpc.org',
    ],
  },
  {
    name: 'Mantle',
    chainId: 5000,
    rpc: [
      'https://rpc.mantle.xyz',
      'https://mantle-mainnet.public.blastapi.io',
      'https://mantle-rpc.publicnode.com',
      'https://mantle.drpc.org',
      'https://rpc.ankr.com/mantle',
      'https://1rpc.io/mantle',
    ],
  },
  {
    name: 'IRIS Hub',
    chainId: 6688,
    rpc: [
      'https://evmrpc.irishub-1.irisnet.org',
      'https://iris-evm-rpc.publicnode.com',
    ],
  },
  {
    name: 'Bitgert Mainnet',
    chainId: 32520,
    rpc: [
      'https://rpc.icecreamswap.com',
      'https://nodes.vefinetwork.org/bitgert',
      'https://flux-rpc.brisescan.com',
      'https://flux-rpc1.brisescan.com',
      'https://flux-rpc2.brisescan.com',
      'https://rpc-1.chainrpc.com',
      'https://rpc-2.chainrpc.com',
      'https://node1.serverrpc.com',
      'https://node2.serverrpc.com',
    ],
  },
  {
    name: 'Base Sepolia Testnet',
    chainId: 84532,
    rpc: [
      'https://rpc.notadegen.com/base/sepolia',
      'https://base-sepolia.blockpi.network/v1/rpc/public',
      'https://public.stackup.sh/api/v1/node/base-sepolia',
    ],
  },
  {
    name: 'Base',
    chainId: 8453,
    rpc: [
      'https://mainnet.base.org',
      'https://developer-access-mainnet.base.org',
      'https://base-mainnet.diamondswap.org/rpc',
      'https://base.blockpi.network/v1/rpc/public',
      'https://1rpc.io/base',
      'https://base-pokt.nodies.app',
      'https://base.meowrpc.com',
      'https://base-mainnet.public.blastapi.io',
      'https://base.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/base',
      'https://rpc.notadegen.com/base',
      'https://base-rpc.publicnode.com',
      'https://base.drpc.org',
      'https://endpoints.omniatech.io/v1/base/mainnet/public',
      'https://base.api.onfinality.io/public',
      'https://public.stackup.sh/api/v1/node/base-mainnet',
      'https://base.rpc.subquery.network/public',
    ],
  },
  {
    name: 'HAQQ Network',
    chainId: 11235,
    rpc: [
      'https://haqq-evm.publicnode.com',
      'https://evm.haqq.sh',
      'https://haqq.drpc.org',
    ],
  },
  {
    name: 'Scroll',
    chainId: 534352,
    rpc: [
      'https://rpc.scroll.io',
      'https://rpc-scroll.icecreamswap.com',
      'https://scroll-mainnet.public.blastapi.io/',
      'https://scroll-mainnet-public.unifra.io',
      'https://scroll.blockpi.network/v1/rpc/public',
      'https://1rpc.io/scroll',
      'https://scroll.drpc.org',
      'https://scroll-mainnet.rpc.grove.city/v1/a7a7c8e2',
      'https://scroll.api.onfinality.io/public',
    ],
  },
  {
    name: 'Scroll Alpha Testnet',
    chainId: 534353,
    rpc: [
      'https://scroll-alpha-public.unifra.io',
      'https://scroll-alphanet.public.blastapi.io',
    ],
  },
  {
    name: 'Sepolia',
    chainId: 11155111,
    rpc: [
      'https://endpoints.omniatech.io/v1/eth/sepolia/public',
      'https://ethereum-sepolia.blockpi.network/v1/rpc/public',
      'https://eth-sepolia.public.blastapi.io',
      'https://eth-sepolia-public.unifra.io',
      'https://sepolia.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/sepolia',
      'https://ethereum-sepolia-rpc.publicnode.com',
      'https://1rpc.io/sepolia',
      'https://eth-sepolia.api.onfinality.io/public',
      'https://ethereum-sepolia.rpc.subquery.network/public',
    ],
  },
  {
    name: 'QuarkChain Mainnet Root',
    chainId: 20181205,
    rpc: [
      'https://hz.rpc.qkiscan.cn',
      'https://rpc1.qkiscan.cn',
      'https://rpc2.qkiscan.cn',
      'https://rpc3.qkiscan.cn',
      'https://rpc1.qkiscan.io',
      'https://rpc2.qkiscan.io',
      'https://rpc3.qkiscan.io',
    ],
  },
  {
    name: 'Neon EVM Mainnet',
    chainId: 245022934,
    rpc: [
      'https://neon-proxy-mainnet.solana.p2p.org',
      'https://neon-mainnet.everstake.one',
      'https://neon-evm.drpc.org',
    ],
  },
  {
    name: 'Palm Testnet',
    chainId: 11297108099,
    rpc: ['https://palm-testnet.public.blastapi.io'],
  },
  {
    name: 'DFK Chain',
    chainId: 53935,
    rpc: [
      'https://avax-pokt.nodies.app/ext/bc/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi/rpc',
      'https://dfkchain.api.onfinality.io/public',
    ],
  },
  {
    name: 'Harmony Mainnet Shard 0',
    chainId: 1666600001,
    rpc: ['https://s1.api.harmony.one', 'https://harmony-1.drpc.org'],
  },
  {
    name: 'Zenith Mainnet',
    chainId: 79,
    rpc: [
      'https://dataserver-us-1.zenithchain.co/',
      'https://dataserver-asia-3.zenithchain.co/',
      'https://dataserver-asia-4.zenithchain.co/',
      'https://dataserver-asia-2.zenithchain.co/',
    ],
  },
  {
    name: 'Rise of the Warbots Testnet',
    chainId: 7777,
    rpc: [
      'https://testnet1.rotw.games',
      'https://testnet2.rotw.games',
      'https://testnet3.rotw.games',
      'https://testnet4.rotw.games',
      'https://testnet5.rotw.games',
    ],
  },
  {
    name: 'Kekchain',
    chainId: 420420,
    rpc: [
      'https://mainnet.kekchain.com',
      'https://rpc2.kekchain.com',
      'https://kek.interchained.org',
      'https://kekchain.interchained.org',
    ],
  },
  {
    name: 'ZKFair Mainnet',
    chainId: 42766,
    rpc: [
      'https://endpoints.omniatech.io/v1/zkfair/mainnet/public',
      'https://zkfair.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'ZKFair Testnet',
    chainId: 43851,
    rpc: ['https://endpoints.omniatech.io/v1/zkfair/testnet/public'],
  },
  {
    name: 'PulseChain Testnet v4',
    chainId: 943,
    rpc: ['https://pulsechain-testnet-rpc.publicnode.com'],
  },
  {
    name: 'Meme Chain',
    chainId: 18159,
    rpc: [
      'https://mainnet-rpc.memescan.io/',
      'https://mainnet-rpc2.memescan.io/',
      'https://mainnet-rpc3.memescan.io/',
      'https://mainnet-rpc4.memescan.io/',
    ],
  },
  {
    name: 'Filecoin Mainnet',
    chainId: 314,
    rpc: [
      'https://api.node.glif.io',
      'https://node.filutils.com/rpc/v1',
      'https://rpc.ankr.com/filecoin',
      'https://filecoin.chainup.net/rpc/v1',
      'https://infura.sftproject.io/filecoin/rpc/v1',
      'https://api.chain.love/rpc/v1',
      'https://filecoin.drpc.org',
    ],
  },
  {
    name: 'Filecoin Calibration Testnet',
    chainId: 314159,
    rpc: ['https://filecoin-calibration.chainup.net/rpc/v1'],
  },
  {
    name: 'LivePlex TESTNET',
    chainId: 50001,
    rpc: ['https://rpc.oracle.liveplex.io'],
  },
  {
    name: 'Loop Network Mainnet',
    chainId: 15551,
    rpc: ['https://api.mainnetloop.com'],
  },
  {
    name: 'Team Blockchain Mainnet',
    chainId: 88888888,
    rpc: ['https://rpc.teamblockchain.team'],
  },
  {
    name: 'Shimmer EVM Testnet',
    chainId: 1072,
    rpc: ['https://json-rpc.evm.testnet.shimmer.network/'],
  },
  {
    name: 'Polygon zkEVM',
    chainId: 1101,
    rpc: [
      'https://rpc.ankr.com/polygon_zkevm',
      'https://rpc.polygon-zkevm.gateway.fm',
      'https://1rpc.io/polygon/zkevm',
      'https://polygon-zkevm.blockpi.network/v1/rpc/public',
      'https://polygon-zkevm-mainnet.public.blastapi.io',
      'https://api.zan.top/node/v1/polygonzkevm/mainnet/public',
      'https://polygon-zkevm.drpc.org',
      'https://endpoints.omniatech.io/v1/polygon-zkevm/mainnet/public',
    ],
  },
  {
    name: 'Linea Mainnet',
    chainId: 59144,
    rpc: [
      'https://linea.blockpi.network/v1/rpc/public',
      'https://1rpc.io/linea',
      'https://linea.drpc.org',
      'https://linea.decubate.com',
    ],
  },
  {
    name: 'Polygon zkEVM Cardona Testnet',
    chainId: 2442,
    rpc: ['https://polygon-zkevm-cardona.blockpi.network/v1/rpc/public'],
  },
  {
    name: 'Linea Sepolia Testnet',
    chainId: 59141,
    rpc: [
      'https://linea-sepolia.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
      'https://linea-sepolia.blockpi.network/v1/rpc/public',
    ],
  },
  {
    name: 'Scroll Sepolia Testnet',
    chainId: 534351,
    rpc: [
      'https://scroll-sepolia.blockpi.network/v1/rpc/public',
      'https://scroll-testnet-public.unifra.io',
      'https://rpc.ankr.com/scroll_sepolia_testnet',
      'https://scroll-public.scroll-testnet.quiknode.pro/',
      'https://scroll-sepolia.chainstacklabs.com',
      'https://scroll-sepolia.drpc.org',
      'https://scroll-testnet.rpc.grove.city/v1/a7a7c8e2',
      'http://scroll-sepolia-rpc.01no.de:8545/',
    ],
  },
  {
    name: 'Markr',
    chainId: 431140,
    rpc: ['https://rpc.markr.io/ext/'],
  },
  {
    name: 'Oasys Mainnet',
    chainId: 248,
    rpc: [
      'https://oasys.blockpi.network/v1/rpc/public',
      'https://oasys-mainnet.rpc.grove.city/v1/167fa7a3',
      'https://oasys-mainnet-archival.rpc.grove.city/v1/167fa7a3',
    ],
  },
  {
    name: 'JFIN Chain',
    chainId: 3501,
    rpc: ['https://rpc.jfinchain.com'],
  },
  {
    name: 'J2O',
    chainId: 35011,
    rpc: ['https://rpc.j2o.io'],
  },
  {
    name: 'Taiko',
    chainId: 167000,
    rpc: [
      'https://rpc.taiko.xyz',
      'https://taiko.blockpi.network/v1/rpc/public',
      'https://rpc.taiko.tools',
      'https://rpc.ankr.com/taiko',
      'https://taiko.drpc.org',
      'https://taiko-mainnet.rpc.porters.xyz/taiko-public',
    ],
  },
  {
    name: 'Taiko Hekla L2',
    chainId: 167009,
    rpc: [
      'https://taiko-hekla.blockpi.network/v1/rpc/public',
      'https://hekla.taiko.tools',
      'https://rpc.ankr.com/taiko_hekla',
      'https://taiko-hekla.drpc.org',
    ],
  },
  {
    name: 'SOMA Network Testnet',
    chainId: 2323,
    rpc: [
      'https://data-testnet-v1.somanetwork.io',
      'https://block-testnet-v1.somanetwork.io',
    ],
  },
  {
    name: 'SOMA Network Mainnet',
    chainId: 2332,
    rpc: [
      'https://data-mainnet-v1.somanetwork.io',
      'https://block-mainnet-v1.somanetwork.io',
    ],
  },
  {
    name: 'Rollux Mainnet',
    chainId: 570,
    rpc: [
      'https://rpc.rollux.com',
      'https://rollux.rpc.syscoin.org',
      'https://rollux.pollum.services',
    ],
  },
  {
    name: 'Syscoin Tanenbaum Testnet',
    chainId: 5700,
    rpc: [
      'https://syscoin-tanenbaum-evm.publicnode.com',
      'https://rpc-testnet.pollum.services',
    ],
  },
  {
    name: 'Rollux Testnet',
    chainId: 57000,
    rpc: ['https://rollux.rpc-testnet.pollum.services'],
  },
  {
    name: 'Arden Chain Mainnet',
    chainId: 7895,
    rpc: ['https://rpc-athena.ardescan.com'],
  },
  {
    name: 'Softnote',
    chainId: 1003,
    rpc: ['https://rpc.softnote.com/'],
  },
  {
    name: 'Oasis Sapphire',
    chainId: 23294,
    rpc: ['https://1rpc.io/oasis/sapphire'],
  },
  {
    name: 'Hybridchain Testnet',
    chainId: 2458,
    rpc: ['https://rpc-testnet.hybridchain.ai/'],
  },
  {
    name: 'Hybridchain Mainnet',
    chainId: 2468,
    rpc: [
      'https://coredata-mainnet.hybridchain.ai/',
      'https://rpc-mainnet.hybridchain.ai/',
    ],
  },
  {
    name: 'JibChain L1',
    chainId: 8899,
    rpc: [
      'https://rpc-l1.jibchain.net',
      'https://rpc-l1.inan.in.th',
      'https://rpc-l1.jbc.aomwara.in.th',
      'https://rpc-l1.jbc.xpool.pw',
      'https://rpc2-l1.jbc.xpool.pw',
    ],
  },
  {
    name: 'Humans Mainnet',
    chainId: 1089,
    rpc: ['https://humans-mainnet-evm.itrocket.net'],
  },
  {
    name: 'Humans Testnet',
    chainId: 4139,
    rpc: ['https://humans-testnet-evm.itrocket.net'],
  },
  {
    name: 'Kroma',
    chainId: 255,
    rpc: ['https://1rpc.io/kroma'],
  },
  {
    name: 'Mode',
    chainId: 34443,
    rpc: ['https://1rpc.io/mode', 'https://mode.drpc.org'],
  },
  {
    name: 'Dymension',
    chainId: 1100,
    rpc: [
      'https://jsonrpc.dymension.nodestake.org',
      'https://dymension.liquify.com/json-rpc',
      'https://dymension-evm.kynraze.com',
      'https://dymension.drpc.org',
    ],
  },
  {
    name: 'Areon Network Mainnet',
    chainId: 463,
    rpc: [
      'https://mainnet-rpc.areon.network',
      'https://mainnet-rpc2.areon.network',
      'https://mainnet-rpc3.areon.network',
      'https://mainnet-rpc4.areon.network',
      'https://mainnet-rpc5.areon.network',
    ],
  },
  {
    name: 'Moonchain',
    chainId: 18686,
    rpc: ['https://rpc.mxc.com'],
  },
  {
    name: 'Q Mainnet',
    chainId: 35441,
    rpc: ['https://rpc.q.org'],
  },
  {
    name: 'Etherlink Mainnet',
    chainId: 42793,
    rpc: [
      'https://node.mainnet.etherlink.com',
      'https://etherlink-mainnet-pub-l5p9tu.zeeve.net/rpc',
    ],
  },
  {
    name: 'Boba Sepolia',
    chainId: 28882,
    rpc: [
      'https://sepolia.boba.network/',
      'https://boba-sepolia.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/boba-sepolia',
    ],
  },
  {
    name: 'LUKSO',
    chainId: 42,
    rpc: [
      'https://rpc.mainnet.lukso.network',
      'https://rpc.lukso.sigmacore.io',
      'https://42.rpc.thirdweb.com',
      'https://lukso.nownodes.io',
    ],
  },
  {
    name: 'B² Network',
    chainId: 223,
    rpc: [
      'https://rpc.bsquared.network',
      'https://b2-mainnet.alt.technology',
      'https://b2-mainnet-public.s.chainbase.com',
      'https://mainnet.b2-rpc.com',
    ],
  },
  {
    name: 'Goldchain',
    chainId: 10222,
    rpc: ['https://glc-dataseed.glscan.io/'],
  },
  {
    name: 'Lycan Chain',
    chainId: 721,
    rpc: [
      'https://rpc.lycanchain.com',
      'https://us-east.lycanchain.com',
      'https://us-west.lycanchain.com',
      'https://eu-north.lycanchain.com',
      'https://eu-west.lycanchain.com',
      'https://asia-southeast.lycanchain.com',
    ],
  },
  {
    name: 'Berachain Artio',
    chainId: 80084,
    rpc: ['https://bartio.rpc.berachain.com', 'https://bartio.drpc.org'],
  },
  {
    name: 'NAL Network',
    chainId: 328527,
    rpc: ['https://rpc.nal.network'],
  },
  {
    name: 'OnChainPoints',
    chainId: 17071,
    rpc: ['https://rpc.onchainpoints.xyz'],
  },
  {
    name: 'Zircuit',
    chainId: 48900,
    rpc: [
      'https://zircuit1-mainnet.p2pify.com',
      'https://zircuit-mainnet.drpc.org',
      'https://zircuit1-mainnet.liquify.com',
    ],
  },
  {
    name: 'Boba BNB Mainnet',
    chainId: 56288,
    rpc: [
      'https://bnb.boba.network',
      'https://replica.bnb.boba.network',
      'https://boba-bnb.gateway.tenderly.co',
      'https://gateway.tenderly.co/public/boba-bnb',
      'https://boba-bnb.drpc.org',
    ],
  },
  {
    name: 'Fraxtal',
    chainId: 252,
    rpc: ['https://rpc.frax.com', 'https://fraxtal.drpc.org'],
  },
  {
    name: 'Immutable zkEVM',
    chainId: 13371,
    rpc: ['https://rpc.immutable.com', 'https://immutable-zkevm.drpc.org'],
  },
  {
    name: 'Lisk Mainnet',
    chainId: 1135,
    rpc: ['https://rpc.api.lisk.com', 'https://lisk.drpc.org'],
  },
  {
    name: 'Open Campus Codex Testnet',
    chainId: 656476,
    rpc: [
      'https://rpc.open-campus-codex.gelato.digital',
      'https://open-campus-codex-sepolia.drpc.org',
    ],
  },
  {
    name: 'Real Network',
    chainId: 111188,
    rpc: ['https://tangible-real.gateway.tenderly.co', 'https://real.drpc.org'],
  },
  {
    name: 'Zora',
    chainId: 7777777,
    rpc: ['https://rpc.zora.energy', 'https://zora.drpc.org'],
  },
  {
    name: 'VCity Testnet',
    chainId: 20230825,
    rpc: ['https://testnet.vcity.app'],
  },
]
